auto_initialize
~~~~~~~~~~~~~~~

**tipo**: ``booleano``  **predefinito**: ``false``

Un'opzione interna: dice se il form va inizializzato automaticamente.
Per tutti i campi, questa opzione dovrebbe essere ``true`` solo per i form radice e, poiché
un bottone non può essere un form intero da solo, è impostato a ``false``. Non
occorre modificare questa opzione e probabilmente non si avrà bisogno di preoccuparsene.
