constraints
~~~~~~~~~~~

**tipo**: array o :class:`Symfony\\Component\\Validator\\Constraint` **predefinito**: ``null``

Consente di allegare uno o più vincoli di validazione a un campo specifico.
Per maggiori informazioni, vedere :ref:`aggiungere la validazione<form-option-constraints>`.
Questa opzione è aggiunta nell'estensione del form
:class:`Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension`.
