pattern
~~~~~~~

**tipo**: ``stringa`` **predefinito**: ``null``

Aggiunge un attributo HTML5 ``pattern`` per restringere un campo input tramite
un'espressione regolare.

.. caution:

    L'attributo ``pattern`` fornisce una validazione lato client, solo
    per convenienza e che non va usata come sostituto di una validazione
    lato server.

.. note:

    Quando si usano vincoli di validazione, questa opzione viene impostata in modo automatico
    per alcuni vincoli, per corrispondere alla validazione lato server.
