property_path
~~~~~~~~~~~~~

**tipo**: ``qualsiasi`` **predefinito**: ``il valore del campo``

I campi mostrano il valore di una proprietà dell'oggetto del dominio del form.
Quando il form è inviato, il valore immesso è scritto nell'oggetto.

Se si vuole sovrascrivere la proprietà che un campo legge e scrive,
si può impostare l'opzione ``property_path``. Il suo valore predefinito è
il nome del campo.
