required
~~~~~~~~

**tipo**: ``booleano`` **predefinito**: ``true``

Se ``true``, sarà reso un `attributo required HTML5`_. La label corrispondente
sarà anche resa con una classe ``required``.

L'attributo è indipendente dalla validazione del form. Nel caso migliore, se si lascia
che Symfony indovini il tipo di campo, il valore di questa opzione sarà indovinato dalle
informazioni di validazione.

.. _`attributo required HTML5`: http://diveintohtml5.info/forms.html
