Tag select, checkbox o bottoni radio
------------------------------------

Questo campo può essere resto come uno tra diversi campi HTML, a seconda
delle opzioni ``expanded`` e ``multiple``:

+------------------------------------------+----------+----------+
| tipo di elemento                         | expanded | multiple |
+==========================================+==========+==========+
| tag select                               | false    | false    |
+------------------------------------------+----------+----------+
| tag select (con attributo ``multiple``   | false    | true     |
+------------------------------------------+----------+----------+
| bottoni radio                            | true     | false    |
+------------------------------------------+----------+----------+
| checkbox                                 | true     | true     |
+------------------------------------------+----------+----------+
