* **Il componente Class Loader**

  * :doc:`/components/class_loader`

* **Il componente Console**

  * :doc:`/components/console`

* **Il componente CSS Selector**

  * :doc:`/components/css_selector`

* **Il componente Dependency Injection**

  * :doc:`/components/dependency_injection/introduction`
  * :doc:`/components/dependency_injection/definitions`

* **Il componente Event Dispatcher**

  * :doc:`/components/event_dispatcher/introduction`
  * :doc:`/components/event_dispatcher/container_aware_dispatcher`
  * :doc:`/components/event_dispatcher/generic_event`

* **Il componente DOM Crawler**

  * :doc:`/components/dom_crawler`

* **Il componente Finder**

  * :doc:`/components/finder`

* **Il componente HTTP Foundation**

  * :doc:`/components/http_foundation/introduction`
  * :doc:`/components/http_foundation/sessions`

* **Il componente Locale**

  * :doc:`/components/locale`

* **Il componente Process**

  * :doc:`/components/process`

* **Il componente Routing**

  * :doc:`/components/routing`

* **Il componente Templating**

  * :doc:`/components/templating`

* **Il componente YAML**

  * :doc:`/components/yaml`
