* **Opzioni di configurazione**:

  Vi siete mai chiesti quali opzioni di configurazione sono disponibili nei
  file come ``app/config/config.yml``? In questa sezione, tutte le configurazioni disponibili
  sono elencate per ogni voce (per esempio ``framework``) che definisce ogni possibile
  sezione della configurazione di Symfony.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* :doc:`Configurare il Kernel (p.e. AppKernel) </reference/configuration/kernel>`

* **Form e validazione**

  * :doc:`Riferimenti dei tipi di campo dei form </reference/forms/types>`
  * :doc:`Riferimenti dei vincoli di validazione </reference/constraints>`
  * :doc:`Riferimenti delle funzioni dei template di Twig </reference/forms/twig_reference>`

* :doc:`Riferimenti sulle estensioni Twig (form, filtri, tag, ecc.) </reference/twig_reference>`

* **Altre aree**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/events`
  * :doc:`/reference/requirements`
