Campi testo
~~~~~~~~~~~

* :doc:`text</reference/forms/types/text>`
* :doc:`textarea</reference/forms/types/textarea>`
* :doc:`email</reference/forms/types/email>`
* :doc:`integer</reference/forms/types/integer>`
* :doc:`money</reference/forms/types/money>`
* :doc:`number</reference/forms/types/number>`
* :doc:`password</reference/forms/types/password>`
* :doc:`percent</reference/forms/types/percent>`
* :doc:`search</reference/forms/types/search>`
* :doc:`url</reference/forms/types/url>`

Campi di scelta
~~~~~~~~~~~~~~~

* :doc:`choice</reference/forms/types/choice>`
* :doc:`entity</reference/forms/types/entity>`
* :doc:`country</reference/forms/types/country>`
* :doc:`language</reference/forms/types/language>`
* :doc:`locale</reference/forms/types/locale>`
* :doc:`timezone</reference/forms/types/timezone>`

Campi data e ora
~~~~~~~~~~~~~~~~

* :doc:`date</reference/forms/types/date>`
* :doc:`datetime</reference/forms/types/datetime>`
* :doc:`time</reference/forms/types/time>`
* :doc:`birthday</reference/forms/types/birthday>`

Altri campi
~~~~~~~~~~~

* :doc:`checkbox</reference/forms/types/checkbox>`
* :doc:`file</reference/forms/types/file>`
* :doc:`radio</reference/forms/types/radio>`

Gruppi di campi
~~~~~~~~~~~~~~~

* :doc:`collection</reference/forms/types/collection>`
* :doc:`repeated</reference/forms/types/repeated>`

Campi nascosti
~~~~~~~~~~~~~~

* :doc:`hidden</reference/forms/types/hidden>`
* :doc:`csrf</reference/forms/types/csrf>`

Campi di base
~~~~~~~~~~~~~

* :doc:`field</reference/forms/types/field>`
* :doc:`form</reference/forms/types/form>`