* :doc:`/components/console/helpers/dialoghelper` (deprecato da 2.5)
* :doc:`/components/console/helpers/formatterhelper`
* :doc:`/components/console/helpers/progressbar`
* :doc:`/components/console/helpers/progresshelper` (deprecato da 2.5)
* :doc:`/components/console/helpers/questionhelper`
* :doc:`/components/console/helpers/table`
* :doc:`/components/console/helpers/tablehelper` (deprecato da 2.5)
