Vincoli di base
~~~~~~~~~~~~~~~

Questi sono i vincoli di base: usarli per asserire cose molto basilari sul
valore delle proprietà o sui valori restituiti dai metodi di un oggetto.

* :doc:`NotBlank </reference/constraints/NotBlank>`
* :doc:`Blank </reference/constraints/Blank>`
* :doc:`NotNull </reference/constraints/NotNull>`
* :doc:`Null </reference/constraints/Null>`
* :doc:`True </reference/constraints/True>`
* :doc:`False </reference/constraints/False>`
* :doc:`Type </reference/constraints/Type>`

Vincoli stringhe
~~~~~~~~~~~~~~~~

* :doc:`Email </reference/constraints/Email>`
* :doc:`Length </reference/constraints/Length>`
* :doc:`Url </reference/constraints/Url>`
* :doc:`Regex </reference/constraints/Regex>`
* :doc:`Ip </reference/constraints/Ip>`
* :doc:`Uuid</reference/constraints/Uuid>`

Vincoli numerici
~~~~~~~~~~~~~~~~

* :doc:`Range </reference/constraints/Range>`

Vincoli di confronto
~~~~~~~~~~~~~~~~~~~~

* :doc:`EqualTo </reference/constraints/EqualTo>`
* :doc:`NotEqualTo </reference/constraints/NotEqualTo>`
* :doc:`IdenticalTo </reference/constraints/IdenticalTo>`
* :doc:`NotIdenticalTo </reference/constraints/NotIdenticalTo>`
* :doc:`LessThan </reference/constraints/LessThan>`
* :doc:`LessThanOrEqual </reference/constraints/LessThanOrEqual>`
* :doc:`GreaterThan </reference/constraints/GreaterThan>`
* :doc:`GreaterThanOrEqual </reference/constraints/GreaterThanOrEqual>`

Vincoli date
~~~~~~~~~~~~

* :doc:`Date </reference/constraints/Date>`
* :doc:`DateTime </reference/constraints/DateTime>`
* :doc:`Time </reference/constraints/Time>`

Vincoli di insiemi
~~~~~~~~~~~~~~~~~~

* :doc:`Choice </reference/constraints/Choice>`
* :doc:`Collection </reference/constraints/Collection>`
* :doc:`Count </reference/constraints/Count>`
* :doc:`UniqueEntity </reference/constraints/UniqueEntity>`
* :doc:`Language </reference/constraints/Language>`
* :doc:`Locale </reference/constraints/Locale>`
* :doc:`Country </reference/constraints/Country>`

Vincoli di file
~~~~~~~~~~~~~~~

* :doc:`File </reference/constraints/File>`
* :doc:`Image </reference/constraints/Image>`

Vincoli finanziari
~~~~~~~~~~~~~~~~~~

* :doc:`CardScheme </reference/constraints/CardScheme>`
* :doc:`Currency </reference/constraints/Currency>`
* :doc:`Luhn </reference/constraints/Luhn>`
* :doc:`Iban </reference/constraints/Iban>`
* :doc:`Isbn </reference/constraints/Isbn>`
* :doc:`Issn </reference/constraints/Issn>`

Altri vincoli
~~~~~~~~~~~~~

* :doc:`Callback </reference/constraints/Callback>`
* :doc:`Expression </reference/constraints/Expression>`
* :doc:`All </reference/constraints/All>`
* :doc:`UserPassword </reference/constraints/UserPassword>`
* :doc:`Valid </reference/constraints/Valid>`
