* **Flusso di lavoro**

  * :doc:`/cookbook/workflow/new_project_git`
  * :doc:`/cookbook/workflow/new_project_svn`

* **Controllori**

  * :doc:`/cookbook/controller/error_pages`
  * :doc:`/cookbook/controller/service`

* **Rotte**

  * :doc:`/cookbook/routing/scheme`
  * :doc:`/cookbook/routing/slash_in_parameter`

* **Gestione di JavaScript e CSS**

  * :doc:`/cookbook/assetic/asset_management`
  * :doc:`/cookbook/assetic/yuicompressor`
  * :doc:`/cookbook/assetic/jpeg_optimize`
  * :doc:`/cookbook/assetic/apply_to_option`

* **Interazione con la base dati (Doctrine)**

  * :doc:`/cookbook/doctrine/file_uploads`
  * :doc:`/cookbook/doctrine/common_extensions`
  * :doc:`/cookbook/doctrine/event_listeners_subscribers`
  * :doc:`/cookbook/doctrine/dbal`
  * :doc:`/cookbook/doctrine/reverse_engineering`
  * :doc:`/cookbook/doctrine/multiple_entity_managers`
  * :doc:`/cookbook/doctrine/custom_dql_functions`

* **Form e validazione**

  * :doc:`/cookbook/form/form_customization`
  * :doc:`/cookbook/form/data_transformers`
  * :doc:`/cookbook/form/dynamic_form_generation`
  * :doc:`/cookbook/form/form_collections`
  * :doc:`/cookbook/form/create_custom_field_type`
  * :doc:`/cookbook/validation/custom_constraint`
  * (doctrine) :doc:`/cookbook/doctrine/file_uploads`

* **Configurazione e contenitore di servizi**

  * :doc:`/cookbook/configuration/environments`
  * :doc:`/cookbook/configuration/external_parameters`
  * :doc:`/cookbook/service_container/factories`
  * :doc:`/cookbook/service_container/parentservices`
  * :doc:`/cookbook/service_container/scopes`
  * :doc:`/cookbook/service_container/tags`
  * :doc:`/cookbook/configuration/pdo_session_storage`

* **Bundle**

  * :doc:`/cookbook/bundles/best_practices`
  * :doc:`/cookbook/bundles/inheritance`
  * :doc:`/cookbook/bundles/override`
  * :doc:`/cookbook/bundles/extension`

* **Email**

  * :doc:`/cookbook/email/email`
  * :doc:`/cookbook/email/gmail`
  * :doc:`/cookbook/email/dev_environment`
  * :doc:`/cookbook/email/spool`

* **Test**

  * :doc:`/cookbook/testing/http_authentication`
  * :doc:`/cookbook/testing/insulating_clients`
  * :doc:`/cookbook/testing/profiling`
  * :doc:`/cookbook/testing/doctrine`

* **Sicurezza**

  * :doc:`/cookbook/security/entity_provider`
  * :doc:`/cookbook/security/remember_me`
  * :doc:`/cookbook/security/voters`
  * :doc:`/cookbook/security/acl`
  * :doc:`/cookbook/security/acl_advanced`
  * :doc:`/cookbook/security/force_https`
  * :doc:`/cookbook/security/form_login`
  * :doc:`/cookbook/security/securing_services`
  * :doc:`/cookbook/security/custom_provider`
  * :doc:`/cookbook/security/custom_authentication_provider`

* **Cache**

  * :doc:`/cookbook/cache/varnish`

* **Template**

  * :doc:`/cookbook/templating/global_variables`
  * :doc:`/cookbook/templating/PHP`
  * :doc:`/cookbook/templating/twig_extension`

* **Strumenti, log e interni**

  * :doc:`/cookbook/logging/monolog`
  * :doc:`/cookbook/logging/monolog_email`

* **Strumenti e interni**

  * :doc:`/cookbook/console/console_command`
  * :doc:`/cookbook/debugging`

* **Servizi web**

  * :doc:`/cookbook/web_services/php_soap_extension`

* **Estendere Symfony**

  * :doc:`/cookbook/event_dispatcher/class_extension`
  * :doc:`/cookbook/event_dispatcher/method_behavior`
  * :doc:`/cookbook/request/mime_type`
  * :doc:`/cookbook/profiler/data_collector`

* **Symfony2 per utenti di symfony1**

  * :doc:`/cookbook/symfony1`
