* **Codice**

  * :doc:`Bug </contributing/code/bugs>`
  * :doc:`Patch </contributing/code/patches>`
  * :doc:`Sicurezza </contributing/code/security>`
  * :doc:`Test </contributing/code/tests>`
  * :doc:`Standard del codice </contributing/code/standards>`
  * :doc:`Convenzioni del codice </contributing/code/conventions>`
  * :doc:`Git </contributing/code/git>`
  * :doc:`Licenza </contributing/code/license>`

* **Documentazione**

  * :doc:`Panoramica </contributing/documentation/overview>`
  * :doc:`Formato </contributing/documentation/format>`
  * :doc:`Standard di documentazione </contributing/documentation/standards>`
  * :doc:`Traduzioni </contributing/documentation/translations>`
  * :doc:`Licenza </contributing/documentation/license>`

* **Comunità**

  * :doc:`Processo di rilascio </contributing/community/releases>`
  * :doc:`Altre risorse </contributing/community/other>`
